services:
  postgres:
    image: postgres:15-alpine
    container_name: media-vault-db
    platform: linux/amd64
    restart: unless-stopped
    environment:
      POSTGRES_DB: mediaVault
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U username -d mediaVault"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: media-vault-backend
    platform: linux/amd64
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=mediaVault
      - DB_USER=username
      - DB_PASSWORD=password
      - PORT=3001
      - NODE_ENV=development
      - UPLOAD_RATE_LIMIT_MAX=10
      - UPLOAD_RATE_LIMIT_WINDOW_MS=300000
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - upload_data:/app/uploads

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: media-vault-frontend
    platform: linux/amd64
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:3001
    depends_on:
      - backend

volumes:
  postgres_data:
    driver: local
  upload_data:
    driver: local

networks:
  default:
    name: media-vault-network