version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: media-vault-db
    platform: linux/amd64  # Add this line to force x86 architecture
    restart: unless-stopped
    environment:
      POSTGRES_DB: mediaVault
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U username -d mediaVault"]
      interval: 10s
      timeout: 5s
      retries: 5


  # React Frontend Application
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: media-vault-frontend
    platform: linux/amd64  # Add this line for consistency
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      # Vite environment variables (prefixed with VITE_)
      - VITE_API_URL=http://localhost:3001
      - VITE_DB_HOST=postgres
      - VITE_DB_PORT=5432
      - VITE_DB_NAME=mediaVault
      - VITE_DB_USER=username
      - VITE_DB_PASSWORD=password
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
    driver: local

networks:
  default:
    name: media-vault-network